version: '2'
services:
  posters:
    image: "postgres:9.5"
    environment:
      DB_USER_NAME: jentrata
      DB_USER_PASS: jentrata
    volumes:
    - ./Dist/src/main/scripts/sql/ebms.sql:/work/sql/ebms.sql
    - ./ContainerFiles/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  jentrata-msh:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - posters
    links:
      - posters:db
    environment:
      TOMCAT_USER_NAME: corvus
      TOMCAT_USER_PASS: corvus
      DB_USER_NAME: jentrata
      DB_USER_PASS: jentrata
      DB_HOST_NAME: db
