//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.09 at 10:45:26 AM EST 
//


package org.jentrata.ebxml.cpa;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}TransportSender" minOccurs="0"/>
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}TransportReceiver" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="transportId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportSender",
    "transportReceiver"
})
@XmlRootElement(name = "Transport")
public class Transport {

    @XmlElement(name = "TransportSender")
    protected TransportSender transportSender;
    @XmlElement(name = "TransportReceiver")
    protected TransportReceiver transportReceiver;
    @XmlAttribute(name = "transportId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String transportId;

    /**
     * Gets the value of the transportSender property.
     * 
     * @return
     *     possible object is
     *     {@link TransportSender }
     *     
     */
    public TransportSender getTransportSender() {
        return transportSender;
    }

    /**
     * Sets the value of the transportSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportSender }
     *     
     */
    public void setTransportSender(TransportSender value) {
        this.transportSender = value;
    }

    /**
     * Gets the value of the transportReceiver property.
     * 
     * @return
     *     possible object is
     *     {@link TransportReceiver }
     *     
     */
    public TransportReceiver getTransportReceiver() {
        return transportReceiver;
    }

    /**
     * Sets the value of the transportReceiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportReceiver }
     *     
     */
    public void setTransportReceiver(TransportReceiver value) {
        this.transportReceiver = value;
    }

    /**
     * Gets the value of the transportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportId() {
        return transportId;
    }

    /**
     * Sets the value of the transportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportId(String value) {
        this.transportId = value;
    }

}
